version : '3'

services:

  web:
    container_name: ${APP_NAME}_web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    environment:
    - MYSQL_DATABASE=dbname
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=12345
    - MYSQL_HOST=db
    ports:
    - "9000:80"
    volumes:
    - .:/var/www
    depends_on:
    - db

  db:
    container_name: ${APP_NAME}_db
    image: mysql:5.7
    ports:
    - "6603:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=654321
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=654321
    - MYSQL_DATABASE=dbname
    volumes:
    - "mysql_data:/var/lib/mysql"
    - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  mysql_data: { driver: local }